### ISSUE TITLE
The code should use tmap

### ISSUE THREAD

**Issue by zross** [mcSamuelDataSci/learnCBD#1]
@mcSamuelDataSci tmap is better here is an example

```r
tm_shape(Europe) +
    tm_polygons("well_being", title="Well-Being Index") +
    tm_facets("part", free.coords=FALSE) +
tm_style_grey()
```

**Comment by mcSamuelDataSci** [comment]
Okay. I have started to "study" tmap, and it does seem great and that I should/will move to that.  It does not seem to specifically help with some of the "cut point" issues I have (and seems to rely on the "classIntervals" function that I was already using to a degree) but will help improve things in a lot of other areas.

**Comment by zross** [comment]
Sounds good. If the cutpoints are an issue you can open a new issue.
