### ISSUE TITLE
Don't continue to re-run tigris scripts, save the shapes and move on

### ISSUE THREAD

**Issue by zross** [mcSamuelDataSci/learnCBD#3]
Your app.R has scripts that read from tigris. Since you really only need to do this once you should do it, save the files and then never do it again. save the script as processing.R or something and don't include the initial prep in your shiny app. I started this as an example here https://github.com/mcSamuelDataSci/learnCBD/tree/zev/initial_edits

**Comment by mcSamuelDataSci** [comment]
I pretty much do what you suggest in the "real" app set up.  In addition to the folder where the app files and sub-folders reside, there is a folder "upstream" that is at a "parallel" level to the app folder where a lot of processing is done that generates shape and data files used by the app.

**Comment by zross** [comment]
Sounds good, but there is a ton of non ui and non server code in the app.R and given the size of the app I would even recommend a ui and a server folder in addition to top level ui.R and server.R files.
