### ISSUE TITLE
Consider using fs package to simplify path creation

### ISSUE THREAD

**Issue by zross** [mcSamuelDataSci/learnCBD#4]
You're using paste0 which can be a pain getting the `/` right. Consider `fs` package example [here](https://github.com/mcSamuelDataSci/learnCBD/blob/55f7768ad84b9a91c6d648cd7c26702972939cc1/processing_scripts/processing.R#L29)

**Comment by mcSamuelDataSci** [comment]
Never-mind...  I got it now.
